export const ETHERS_WALLET_BUILDER_OPTIONS = "ETHERS_WALLET_BUILDER_OPTIONS";
export const ETHERS_CONTRACT_BUILDER_OPTIONS = "ETHERS_CONTRACT_BUILDER_OPTIONS";
export const ETHERS_LISTENER_TYPE = "ETHERS_LISTENER_TYPE";
export const ETHERS_LISTENER_ON_BLOCK_OPTIONS = "ETHERS_LISTENER_ON_BLOCK_OPTIONS";
export const ETHERS_LISTENER_ON_EVENT_OPTIONS = "ETHERS_LISTENER_ON_EVENT_OPTIONS";
export const ETHERS_ARGS_KEY = "ETHERS_ARGS_KEY";
